### ISSUE TITLE
Cambiar la imagen de fondo

### ISSUE THREAD

**Issue by FiliSantillan** [comunidad-codigofacilito/gitfacilito#2]
# Cambiar la imagen de fondo

Alguien que me apoye cambiando la imagen de fondo, por algo realmente épico :+1:

**Comment by afcanop** [comment]
ayudare con esta  pero tengo una pregunta no estoy como colaborador del proyecto entonces como puedo subir los  cambios??? gracias

**Comment by FiliSantillan** [comment]
Cool :+1: 

@afcanop En la clase siete que probablemente se suba hoy (domingo) se va a explicar esa parte de como colaborar, aunque no seas parte del proyecto :smile:

**Comment by FiliSantillan** [comment]
Ya se cambio la imagen de fondo :smile: 

Gracias @josealvaradoo :+1: 

Aquí el merge ==> a9917a4c144daf082bbf050fd77454af8b5f157b

**Comment by theoxt** [comment]
😄
