### ISSUE TITLE
Rama gh-pages

### ISSUE THREAD

**Issue by cristhianCMH** [comunidad-codigofacilito/gitfacilito#21]
# Gh-pages

Hola! deberias de colocar el link sobre la rama gh-pages, para poder ver el proyecto como se ve , saludos

**Comment by FiliSantillan** [comment]
Master es en donde las personas están mandando sus cambios (Pull Request).

Ya página se ve increíble y tranquilo yo iré subiendo todos esos cambios a gh-pages

:link: ==> http://comunidad-codigofacilito.github.io/gitfacilito/
