### ISSUE TITLE
Cambiar banner negro del header

### ISSUE THREAD

**Issue by davidcgarcia** [comunidad-codigofacilito/gitfacilito#25]
# Cambiar banner negro del header

Hola quetal, me parece que debería eliminarse el banner negro del `header`, creo que la página se ve mejor si el.

**Comment by josealvaradoo** [comment]
Hola david, ayer se hizo un **Pull Request** con ese cambio y se hizo el merge a la rama master. Habrá que **actualizar la rama gh-pages** para que se vean los cambios. :-)
