### ISSUE TITLE
Hay que mejorar el peso de las imagenes

### ISSUE THREAD

**Issue by carlosandresal** [comunidad-codigofacilito/gitfacilito#27]
Se tienen que mejorar el peso de las imagines y las rutas para hacer que la carga sea mas rápido.
se deberia cambiar el peso del backgroun y hacer que la ruta sea: 
background-image: url(../images/background.png); estoy mejora el tiempo de carga

**Comment by FiliSantillan** [comment]
Se mejoro el peso de las imágenes, muchas gracias @studioArtbliss 

Tu pull request ya fue aceptado, aquí el merge :point_right: 3c8cab41db8435048db04d3c888ff2b4dcd6b92a
