### ISSUE TITLE
Agregar todos los videos de la clase de Git 

### ISSUE THREAD

**Issue by FiliSantillan** [comunidad-codigofacilito/gitfacilito#4]
# Agregar todos los videos de la clase de Git

¿Qué les parece si agregamos todos los videos del curso de git?

En cuando estén todos los videos en youtube, creamos otra sección en donde estén todos incluidos con la etiqueta de `<iframe></iframe>` de Youtube.

¿Qué dicen?

**Comment by gereyes** [comment]
## Hola

A mi me parece bien, :+1: .

##### Saludos.

**Comment by alfieris** [comment]
# Buena idea

Sería buenísimo hacer eso de los videos..

**Comment by FiliSantillan** [comment]
@alfieris Te gustaría apoyarnos en esa parte ?

**Comment by cesarcruzc** [comment]
Hola aparte podemos agregar las presentaciones debajo del video que les parece?

**Comment by ronald948** [comment]
Interesante recien vi el Video 5 de Git por eso estoy aqui, espero con ansias los demas videos y si puedo ayudar con algo seria buena idea.

**Comment by f4ak4a** [comment]
Recien termine el video 5! buenisimos tus videos! quisiera tu canal de youtube si los estas subiendo por ahi, para poder seguir con esto.. o saber si los vas a subir a codigofacilito? 

Saludos.

**Comment by Topi99** [comment]
Hola,  @FiliMX  yo podría ayudar en esa parte

**Comment by FiliSantillan** [comment]
@cesarcruzc Estaría muy bien :) 

@ronald948 Perfecto :D

@f4ak4a Ya esta el curso completo :D

@Topi99 Déjame ver, hoy empezare a aceptar los pull request :+1:

**Comment by cristhianCMH** [comment]
genial!

**Comment by FiliSantillan** [comment]
# Videos del curso

@nayeldavila agrego muchos cambios, entre ellos los videos del curso.

Muchas gracias :+1: 

Aquí el merge: e4c3d860d2a35c8cebae2564962e7482fe7c7ce7
