### ISSUE TITLE
Cambiar tipo de fuente

### ISSUE THREAD

**Issue by FiliSantillan** [comunidad-codigofacilito/gitfacilito#5]
# Cambiar tipo de fuente

¿Qué les parece si cambiamos el estilo de fuente de los títulos y párrafos?

Usando Google Fonts: https://www.google.com/fonts :facepunch:

**Comment by mauri01** [comment]
Pienso que estaría bien cambiar el tipo de fuente.
Encontré una que quizás podrías agregar:
CSS: `font-family: 'Nunito', sans-serif;`
Utilizando Google Fonts :+1:

**Comment by FiliSantillan** [comment]
Perfecto, esa fuente estaría muy bien para los títulos. ¿Ahora que tal una para el resto del texto? 

La idea es que los estudiantes hagan parte de esto, así que, ¿Porque no agregas tú?
En la clase número 7 se va a ver esa parte para que puedan colaborar :+1:

**Comment by gereyes** [comment]
Me gusta la idea de colaborar, lastima que aun no se html ni css jaja, Bueno mientras colaboro con los Issues.

**Comment by afcanop** [comment]
hola excelente curso como puedo ayudar

**Comment by FiliSantillan** [comment]
@Genesisj96Dev Puedes ayudar en lo que tu quieras, no importa que sea algo básico, lo que importa es que colabores :smiley: 

@afcanop ¿Por qué no me apoyas con otro issue de los que están abiertos?, toma el que gustes.

Por cierto hoy (Domingo) hay una clase interesante y que les va a ayudar a mandarme su código, se ras recomiendo mucho. :facepunch:

**Comment by alfieris** [comment]
Me parece excelente la iniciativa de FiliMX... excelente curso !! Cuenten conmigo para apoyar al grupo.
:+1:

**Comment by FiliSantillan** [comment]
# Cambio de Fuente Listo :+1:

Se acepto un **"Pull Request"** sobre el cambio de fuente.

Aquí el merge: 214188d66a130909efd92ec350e463089d216346

Gracias @mauri01
