### ISSUE TITLE
Hice una mejora en los botones pero no se como mandartelo de forma correcta

### ISSUE THREAD

**Issue by EmanuelEsquibel** [comunidad-codigofacilito/gitfacilito#6]
https://github.com/EmanuelEsquibel/ForkCodigoFacilito.git

**Comment by FiliSantillan** [comment]
Hola @EmanuelEsquibel 

En la clase número siete que probablemente se suba hoy (Domingo) a youtube se va a explicar como mandar tus botones, espérala y los envías :smile:

**Comment by dtavera** [comment]
Muy buenas las clases :+1:. Espero la clase de hoy domingo. Meteré todos mis proyectos en github :smiley:

**Comment by FiliSantillan** [comment]
@dtavera Excelente :+1: 

Hablando de la clase, acaban de subirla: https://www.youtube.com/watch?v=VMInoluaZ9o jaja

**Comment by dtavera** [comment]
perfecto! @FiliMX :grin:
